console.log("Përshendetje Botë!");
console.log("مرحبا بالعالم!");
console.log("Kaixo Mundua!");
console.log("Pozdrav svijete!");
console.log("Hej Verden!");
console.log("Bonjour le monde!");
console.log("Hallo Welt!");
console.log("Ciao mondo!");
console.log("こんにちは世界！");
console.log("Olá Mundo!");